/* 
 * OpenAPI spec version: 2.4.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type Address struct {

	Address1 string `json:"address1,omitempty"`

	Address2 string `json:"address2,omitempty"`

	City string `json:"city,omitempty"`

	// State or province or territory
	State string `json:"state,omitempty"`

	// Postal or zip code
	PostalCode string `json:"postalCode,omitempty"`

	// Two-letter ISO country code to be used as a hint for target region<br/><br/> NOTE: These are sample values, there are many <a href='http://www.iso.org/iso/country_codes.htm'>more</a>
	Country string `json:"country,omitempty"`
}
