/* 
 * OpenAPI spec version: 2.4.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type DnsRecordCreateTypeName struct {

	Data string `json:"data,omitempty"`

	// Record priority (MX and SRV only)
	Priority int32 `json:"priority,omitempty"`

	Ttl int32 `json:"ttl,omitempty"`

	// Service type (SRV only)
	Service string `json:"service,omitempty"`

	// Service protocol (SRV only)
	Protocol string `json:"protocol,omitempty"`

	// Service port (SRV only)
	Port int32 `json:"port,omitempty"`

	// Record weight (SRV only)
	Weight int32 `json:"weight,omitempty"`
}
