/* 
 * OpenAPI spec version: 2.4.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type DomainAvailableResponse struct {

	// Domain name
	Domain string `json:"domain,omitempty"`

	// Whether or not the domain name is available
	Available bool `json:"available,omitempty"`

	// Whether or not the `available` answer has been definitively verified with the registry
	Definitive bool `json:"definitive,omitempty"`

	// Price of the domain excluding taxes or fees. Only returned if tld is offered
	Price int32 `json:"price,omitempty"`

	// Currency in which the `price` is listed. Only returned if tld is offered
	Currency string `json:"currency,omitempty"`

	// Number of years included in the price. Only returned if tld is offered
	Period int32 `json:"period,omitempty"`
}
