/* 
 * OpenAPI spec version: 2.4.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type DomainPurchaseResponse struct {

	// Unique identifier of the order processed to purchase the domain
	OrderId int32 `json:"orderId,omitempty"`

	// Number items included in the order
	ItemCount int32 `json:"itemCount,omitempty"`

	// Total cost of the domain and any selected add-ons
	Total int32 `json:"total,omitempty"`

	// Currency in which the `total` is listed
	Currency string `json:"currency,omitempty"`
}
