/* 
 * OpenAPI spec version: 2.4.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type DomainTransferIn struct {

	// Authorization code from registrar for transferring a domain
	AuthCode string `json:"authCode,omitempty"`

	// Can be more than 1 but no more than 10 years total including current registration length
	Period int32 `json:"period,omitempty"`

	// Whether or not the domain should be configured to automatically renew
	RenewAuto bool `json:"renewAuto,omitempty"`

	// Whether or not privacy has been requested
	Privacy bool `json:"privacy,omitempty"`

	// Required agreements can be retrieved via the GET ./domains/agreements endpoint
	Consent Consent `json:"consent,omitempty"`
}
