/* 
 * OpenAPI spec version: 2.4.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type DomainPurchase struct {

	// For internationalized domain names with non-ascii characters, the domain name is converted to punycode before format and pattern validation rules are checked
	Domain string `json:"domain,omitempty"`

	Consent Consent `json:"consent,omitempty"`

	Period int32 `json:"period,omitempty"`

	NameServers []string `json:"nameServers,omitempty"`

	RenewAuto bool `json:"renewAuto,omitempty"`

	Privacy bool `json:"privacy,omitempty"`

	ContactRegistrant Contact `json:"contactRegistrant,omitempty"`

	ContactAdmin Contact `json:"contactAdmin,omitempty"`

	ContactTech Contact `json:"contactTech,omitempty"`

	ContactBilling Contact `json:"contactBilling,omitempty"`
}
