/* 
 * OpenAPI spec version: 2.4.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type IdentityDocumentCreate struct {

	IdentificationType string `json:"identificationType,omitempty"`

	// Domain for which Real Name Validation must be completed
	Domain string `json:"domain,omitempty"`

	// Individual or business name written on the document. Must match image exactly
	LegalEntityName string `json:"legalEntityName,omitempty"`

	// Individual or business identification number written on the document. Must match image exactly
	IdentificationNumber string `json:"identificationNumber,omitempty"`

	// The base64 encoded string of the document image. The document image must be in JPEG format with a file size between 4KB and 2MB
	Image string `json:"image,omitempty"`

	Consent Consent `json:"consent,omitempty"`
}
