/*
 * OpenAPI spec version: 2.4.9
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type JsonProperty struct {
	Type_ string `json:"type,omitempty"`

	Ref string `json:"$ref,omitempty"`

	Items interface{} `json:"items,omitempty"`

	Required bool `json:"required,omitempty"`

	MaxItems int32 `json:"maxItems,omitempty"`

	MinItems int32 `json:"minItems,omitempty"`

	DefaultValue string `json:"defaultValue,omitempty"`

	Format string `json:"format,omitempty"`

	Pattern string `json:"pattern,omitempty"`

	Maximum int32 `json:"maximum,omitempty"`

	Minimum int32 `json:"minimum,omitempty"`
}
